module: default
version: 1
runtime: go
api_version: go1
vm: true

manual_scaling:
  instances: 1

network:
  forwarded_ports:
  - 5050

handlers:
- url: /examples
  static_dir: static/todomvc/examples

- url: /learn.json
  static_files: static/todomvc/learn.json
  upload: static/todomvc/learn\.json

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: _go_app
